# Generated by Django 3.0.8 on 2020-08-01 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 16, 17, 31, 747694)),
        ),
    ]
