# Generated by Django 3.0.8 on 2020-08-01 14:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0003_auto_20200801_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
