# Generated by Django 3.0.8 on 2020-08-01 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0004_ledger_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger',
            name='date',
        ),
        migrations.AddField(
            model_name='ledger',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
