# Generated by Django 3.0.8 on 2020-08-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0005_auto_20200801_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
