# Generated by Django 3.0.8 on 2020-08-01 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0006_auto_20200801_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger',
            name='timestamp',
        ),
    ]
