# Generated by Django 3.0.8 on 2020-08-01 15:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0007_remove_ledger_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
